### ISSUE TITLE
Client Cache Deserilazation with Claims

### ISSUE THREAD

**Issue by jlegan** [imperugo/IdentityServer3.Contrib.Cache.Redis#2]
Hope all is well with you. 

I hit an issue today which was nearly identical to an issue I reported previously (https://github.com/imperugo/IdentityServer3.Contrib.Cache.Redis/issues/1). 

It is also related to the serialization of claims but now in the client cache. I believe the fix you put in was specific to the user store. Below is a dump of the trace log. I am currently running the latest nuget packages.

```
iisexpress.exe Error: 0 : [IdentityServer3.Core.Configuration.Hosting.ErrorPageFilterAttribute]: 7/1/2015 2:40:48 PM +00:00 -- Exception accessing: /core/login
Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type System.Security.Claims.Claim. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Claims[0].Issuer', line 1, position 1007.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at StackExchange.Redis.Extensions.Newtonsoft.NewtonsoftSerializer.Deserialize[T](Byte[] serializedObject)
   at StackExchange.Redis.Extensions.Newtonsoft.NewtonsoftSerializer.<>c__DisplayClassb`1.<DeserializeAsync>b__a()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by jlegan** [comment]
I fixed it in a similar fashion within my GetAsync implementation. The following code works fine.

```
public async Task<Client> GetAsync(string key)
            {
                var result = await _cacheClient.GetAsync<object>(key);

                if (result != null)
                {
                    return await Task.FromResult(result as Client);
                }

                return await Task.FromResult<Client>(null);
            }
```

**Comment by Davidsual** [comment]
Hi jlegan,

Thank you for posting about this issue.

I get this issue in the class TokenHandleStoreService : ITokenHandleStore

precisely in the method:

```
        public async Task<Token> GetAsync(string key)
        {
            if (_cacheProvider.Exists(key))
            {
               return await Task.FromResult(_cacheProvider.Get<Token>(key));                
            }
            return await Task.FromResult<Token>(null);
        }
```

IdentityServer try to get from Redis the Token.

During the method return await Task.FromResult(_cacheProvider.Get<Token>(key));  

I get the error: "Unable to find a constructor to use for type System.Security.Claims.Claim....."

In this case is the entire token that need to be deserialized.

**Comment by jlegan** [comment]
What version of IdentityServer are you running, what version of StackExchange Redis and what version of Newtonsoft? Might be easier to paste in your packages.config.

**Comment by Davidsual** [comment]
Hi James,

thank you for replying me.
I admit that I posted this issue on wrong forum, this issue is related to IdentityServer3.

I reopened the issue here:
https://github.com/IdentityServer/IdentityServer3/issues/1862

Basically in IdentityServer3 2.0.1 I implemented a custom ITokenHandleStore with the purpose of storing in Redis cache the object.

IdentityServer3.Core.Models.Token

Serializing in json this class is not a problem, the problem is de-serialize it because System.Security.Claim doesn't have a default constructor, therefore JSON.Net raises an exception.

Brock Allen replied me:
Your cache implementation needs to map to some simple data structure and not rely upon serializing the claim class.

it makes sense.

Hope it can be useful to someone.

Davide

**Comment by imperugo** [comment]
Can I close this?

**Comment by farshid3003** [comment]
Are you sure? 
test it : here
if (result != null)
            {
                var res = await Task.FromResult(result as IEnumerable<Claim>);
                return res; // Every time it is Null. 
            }
you did not solve it. every time you read it from db again
you have this problem in ClientStoreCache as well when you have client claims

**Comment by farshid3003** [comment]
Solution for user:

add a custom json converter

```
public class ClaimConverter : JsonConverter
{
    public override bool CanConvert(Type objectType)
    {
        return (objectType == typeof(System.Security.Claims.Claim));
    }

    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
        JObject jo = JObject.Load(reader);
        string type = (string)jo["Type"];
        string value = (string)jo["Value"];
        string valueType = (string)jo["ValueType"];
        string issuer = (string)jo["Issuer"];
        string originalIssuer = (string)jo["OriginalIssuer"];
        return new Claim(type, value, valueType, issuer, originalIssuer);
    }

    public override bool CanWrite
    {
        get { return false; }
    }

    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
        throw new NotImplementedException();
    }
}
```

use it like this:

```
    public async Task<IEnumerable<Claim>> GetAsync(string key)
    {
        var result = await cacheClient.GetAsync<object>(key);

        if (result != null)
        {
            IEnumerable<Claim> claims = JsonConvert.DeserializeObject<IEnumerable<Claim>>(result.ToString(), new ClaimConverter());
            return claims;
        }

        return await Task.FromResult<IEnumerable<Claim>>(null);
    }
```

and you should use it for clients as well

```
    public async Task<Client> GetAsync(string key)
    {
        var result = await cacheClient.GetAsync<object>(key);

        if (result != null)
        {
            Client client = JsonConvert.DeserializeObject<Client>(result.ToString(), new ClaimConverter());
            return client;
        }

        return await Task.FromResult<Client>(null);
    }
```

**Comment by farshid3003** [comment]
by the way I solve it by another way
I implement a wrapper for cache client and in this wrapper add my custom claim converter to the setting and it works as a charm 

```
            var settings = new Newtonsoft.Json.JsonSerializerSettings();
            settings.Converters.Add(new ClaimConverter());
            serializer = new NewtonsoftSerializer(settings);
```

**Comment by imperugo** [comment]
Hi, 
if you send a PR, I'll merge and update all dependencies.

Let me know
.u

**Comment by farshid3003** [comment]
it is OK by me 
I will open a new branch and change it 
OK ?

**Comment by imperugo** [comment]
I think you can work also on a master and send a PR directly from there

**Comment by farshid3003** [comment]
OK I want to add a optional cache prefix as well. in share redis cache environments it is really needed to have a prefix for cache keys.

**Comment by farshid3003** [comment]
dear imperugo, I dont have access to your branch to commit. I thing for pull request i need to push my code some where. would you please give me access to a new branch to push my codes there and create PR?

**Comment by imperugo** [comment]
You don't need to have access to the repo to open a PR.
The flow should be fork => commit => PR.

Anyway looking here https://github.com/farshid3003/IdentityServer3.Contrib.Cache.Redis I can't see your changes, please push them to your fork and I'll merge it manually.

Thanks
.u

**Comment by farshid3003** [comment]
Ok I did it now

**Comment by imperugo** [comment]
I've create the PR for you
Take a look here https://github.com/imperugo/IdentityServer3.Contrib.Cache.Redis/pull/9 to be sure everything is ok

**Comment by farshid3003** [comment]
Every thigs is ok. Just you can add new feature cache prefix to the documents
Now you can add Cache:Keyprefix unde application setting in web config to customize key prefix. By default it uses idschache as prefix

**Comment by imperugo** [comment]
Deployed just now on nuget.
Please let me know.

Thx
